kind: Deployment
apiVersion: apps/v1
metadata:
  name: upload-deployment
  namespace: upload-api
  labels:
    app: upload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: local/upload-app
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: '-Xmx512m -Xms256m'
            - name: SPRING_PROFILES_ACTIVE
              value: 'prod,api-docs'
            - name: DATABASE_URL
              value: 'mongo-upload-service.upload-db.svc.cluster.local'
            - name: DB_PORT
              value: '27018'
            - name: DB_USER
              value: 'file'
            - name: DB_PASSWORD
              value: 'upload'
            - name: PORT
              value: '8080'
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: 'kafka-service.queue.svc.cluster.local:9092'
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"