server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: file
      password: storage
      database: file_storage

  web:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    root: INFO