apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: db
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "file"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "storage"
          volumeMounts:
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d/init-mongo.js
              subPath: init-mongo.js
      volumes:
        - name: mongo-init-script
          configMap:
            name: mongo-init-script
            items:
              - key: init-mongo.js
                path: init-mongo.js