apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-storage-deployment
  namespace: storage-db
  labels:
    app: mongodb-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-storage
  template:
    metadata:
      labels:
        app: mongodb-storage
    spec:
      containers:
        - name: mongodb-storage
          image: mongo:8.0.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "file"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "storage"
          volumeMounts:
            - name: mongo-storage-init-script
              mountPath: /docker-entrypoint-initdb.d/init-storage-mongo.js
              subPath: init-storage-mongo.js
      volumes:
        - name: mongo-storage-init-script
          configMap:
            name: mongo-storage-init-script
            items:
              - key: init-storage-mongo.js
                path: init-storage-mongo.js