apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-storage-init-script
  namespace: storage-db
data:
  init-storage-mongo.js: |
    db = db.getSiblingDB('file_storage');
    db.createCollection('files');
    db.createUser({
        user: 'file',
        pwd: 'storage',
        roles: [ { role: "readWrite", db: "file_storage" } ]
    });